### ISSUE TITLE
Top-level Module Named Hashring conflicts with other libraries

### ISSUE THREAD

**Issue by geofflane** [bitwalker/libring#15]
https://github.com/discordapp/ex_hash_ring has the exact same module name.

**Comment by bitwalker** [comment]
This is on them, `libring` has been around significantly longer :)

**Comment by bitwalker** [comment]
Thanks for reporting it though, I'll keep an eye on things, particularly the discussion in discordapp/ex_hash_ring#3

**Comment by geofflane** [comment]
It just feels like top-level modules without a namespace are a bad hygiene (for lack of a better term). This came through transitive dependencies between two different libraries (quantum uses swarm which uses libring & redlock uses ex_hash_ring).

**Comment by bitwalker** [comment]
I agree in general - I avoid "namespaceless" modules as a rule; the exception here (for me anyway) was that the datastructure itself _is_ the namespace. I did extensive research to make sure there were no pre-existing modules with that name on Hex or on GitHub as well. I'm not trying to say I don't hold some blame here, but it seems to me that Discord failed to do even basic discovery for existing consistent hash ring libraries, and as a result we have a conflict. There are over 34k downloads of `libring`, and just over 600 downloads of `ex_hash_ring` - renamespacing `libring` is significantly more of an issue than doing so with `ex_hash_ring` at this point - ultimately this is why I'm saying it is on them. If it's causing enough pain for enough people, and Discord isn't going to renamespace, then I'll revisit the issue so the community gets some kind of solution in the end.

**Comment by geofflane** [comment]
@bitwalker Sorry, didn't mean to point too much blame your way. It's definitely hard with things that are non-domain specific data structures like this. And, I agree, all else being equal you win by virtue of being first.

**Comment by bitwalker** [comment]
No worries :) - I had hoped that if any other hash ring library popped up, that they'd see this library, and avoid the conflict; but I shouldn't have assumed that. In the near term, I can provide a branch which renames the modules to something else, so that you can at least carry on without the conflict - you won't be able to use the Hex package, but at least you'll have something you can use.

**Comment by bitwalker** [comment]
You can use the `no-conflict` branch as a workaround :)

**Comment by gmjosack** [comment]
I'm going to be pushing a fix to `ex_hash_ring` today to add a namespace.

**Comment by bitwalker** [comment]
Thanks @gmjosack! Sorry for the trouble!

**Comment by gmjosack** [comment]
No worries at all!
